version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/cortex
hooks:
  ApplicationStop:
    - location: Appstop.sh
      timeout: 20
      runas: ubuntu

  ApplicationStart:
    - location: Appstart.sh
      timeout: 20
      runas: ubuntu
