defaults: &defaults
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'] || 'cortex_development' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] || 'uvzlo1' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '9rDfSu4uYnqqrzj' %>
  host: <%= ENV['DATABASE_HOST'] || '172.31.42.15' %>
  port: <%= ENV['DATABASE_PORT'] || '5432' %>

test:
  <<: *defaults
  database: <%= ENV['TEST_DATABASE_NAME'] || 'cortex_test' %>

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
