defaults: &defaults
  adapter: postgresql
  database: <%= ENV['DATABASE_NAME'] || 'cortex_dev' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] || '' %>
  password: <%= ENV['DATABASE_PASSWORD'] || '' %>
  host: <%= ENV['DATABASE_HOST'] || '' %>
  port: <%= ENV['DATABASE_PORT'] || '' %>

test:
  <<: *defaults
  database: <%= ENV['TEST_DATABASE_NAME'] || 'cortex_test' %>

development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
